// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_fetch_calendar_events from "./routes/api/fetch-calendar-events.ts";
import * as $api_fetch_calendar_svg from "./routes/api/fetch-calendar-svg.ts";
import * as $api_svg_to_png from "./routes/api/svg-to-png.ts";
import * as $index from "./routes/index.tsx";
import * as $DiscordWebhook from "./islands/DiscordWebhook.tsx";
import * as $EventFormatter from "./islands/EventFormatter.tsx";
import * as $FormContainer from "./islands/FormContainer.tsx";
import * as $LocalStorageInput from "./islands/LocalStorageInput.tsx";
import * as $ResultsDisplay from "./islands/ResultsDisplay.tsx";
import * as $URLInput from "./islands/URLInput.tsx";
import * as $WeekPicker from "./islands/WeekPicker.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
	routes: {
		"./routes/_404.tsx": $_404,
		"./routes/_app.tsx": $_app,
		"./routes/api/fetch-calendar-events.ts": $api_fetch_calendar_events,
		"./routes/api/fetch-calendar-svg.ts": $api_fetch_calendar_svg,
		"./routes/api/svg-to-png.ts": $api_svg_to_png,
		"./routes/index.tsx": $index,
	},
	islands: {
		"./islands/DiscordWebhook.tsx": $DiscordWebhook,
		"./islands/EventFormatter.tsx": $EventFormatter,
		"./islands/FormContainer.tsx": $FormContainer,
		"./islands/LocalStorageInput.tsx": $LocalStorageInput,
		"./islands/ResultsDisplay.tsx": $ResultsDisplay,
		"./islands/URLInput.tsx": $URLInput,
		"./islands/WeekPicker.tsx": $WeekPicker,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
